del ".\Localizer\Plugins\*.pdb"
del ".\Localizer\Plugins\*.dll.config"
del ".\Localizer\Plugins\Terraria.exe"
del ".\Localizer\Plugins\TerrariaHooks.dll"
del ".\Localizer\Plugins\Steamworks.NET.dll"
del ".\Localizer\Plugins\ReLogic.dll"
del ".\Localizer\Plugins\Ninject.dll"
del ".\Localizer\Plugins\Newtonsoft.Json.dll"
del ".\Localizer\Plugins\MonoMod.*.dll"
del ".\Localizer\Plugins\Mono.Cecil.dll"
del ".\Localizer\Plugins\log4net.dll"
del ".\Localizer\Plugins\Localizer.dll"
del ".\Localizer\Plugins\0Harmony.dll"
del ".\Localizer\Plugins\System.*.dll"

".\References\Terraria" -build ".\Localizer" -unsafe